routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|   
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//user's home routes 
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home_parent', 'ParentHomeController@index')->name('homeParent');
Route::get('/home_staff', 'StaffHomeController@index')->name('homeStaff');
Route::get('/home_student', 'StudentHomeController@index')->name('homeStudent');
Route::get('/home_teacher', 'TeacherHomeController@index')->name('homeTeacher');
Route::get('/home_web', 'WebController@index')->name('homeWeb');
//controlling user's home routes
Route::get('/Home', 'ControlHome@show')->name('Home');
//web admin login routes 
Route::get('webAdmin', 'webAdmin\Auth\LoginController@showLoginForm')->name('webAdmin');
Route::post('webAdmin', 'webAdmin\Auth\LoginController@login');
//controlling user's login routes
Route::get('login-admin', 'ControlLogin@showLoginForm')->name('login.admin');
Route::post('login-admin', 'ControlLogin@login');
//user's login routes 
Route::get('login-school', 'schoolAdmin\Auth\LoginController@showLoginForm')->name('school.login');
Route::post('login-school', 'schoolAdmin\Auth\LoginController@login');

Route::get('login-parent', 'Parent\Auth\LoginController@showLoginForm')->name('login.parent');
Route::post('login-parent', 'Parent\Auth\LoginController@login');

Route::get('login-student', 'Student\Auth\LoginController@showLoginForm')->name('login.student');
Route::post('login-student', 'Student\Auth\LoginController@login');

Route::get('login-staff', 'Staff\Auth\LoginController@showLoginForm')->name('login.staff');
Route::post('login-staff', 'Staff\Auth\LoginController@login');

Route::get('login-teacher', 'Teacher\Auth\LoginController@showLoginForm')->name('login.teacher');
Route::post('login-teacher', 'Teacher\Auth\LoginController@login');
//////////////////////////////////////////////

//forgot and reset pass
Route::get('forgotPass', 'ControlForgotPass@showEmail')->name('forgotPass');
Route::post('forgotPass', 'ControlForgotPass@reset');

//web admin routes
Route::post('web-passwords/email', 'webAdmin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('web-passwords.email');
Route::get('web-passwords/reset', 'webAdmin\Auth\ForgotPasswordController@showLinkRequestForm')->name('web-passwords.request');
Route::post('web-passwords/reset', 'webAdmin\Auth\ResetPasswordController@reset');
Route::post('web-passwords/reset/{token}', 'webAdmin\Auth\ResetPasswordController@showResetForm')->name('web-passwords.reset');
/////////////////////////////////////////////////

//school admin routes
Route::post('admin-passwords/email', 'schoolAdmin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin-passwords.email');
Route::get('admin-passwords/reset', 'schoolAdmin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin-passwords.request');
Route::post('admin-passwords/reset', 'schoolAdmin\Auth\ResetPasswordController@reset');
Route::post('admin-passwords/reset/{token}', 'schoolAdmin\Auth\ResetPasswordController@showResetForm')->name('admin-passwords.reset');
/////////////////////////////////////////////////

//teacher routes
Route::post('teacher-passwords/email', 'Teacher\Auth\ForgotPasswordController@sendResetLinkEmail')->name('teacher-passwords.email');
Route::get('teacher-passwords/reset', 'Teacher\Auth\ForgotPasswordController@showLinkRequestForm')->name('teacher-passwords.request');
Route::post('teacher-passwords/reset', 'Teacher\Auth\ResetPasswordController@reset');
Route::post('teacher-passwords/reset/{token}', 'Teacher\Auth\ResetPasswordController@showResetForm')->name('teacher-passwords.reset');
/////////////////////////////////////////////////

//student routes
Route::post('student-passwords/email', 'Student\Auth\ForgotPasswordController@sendResetLinkEmail')->name('student-passwords.email');
Route::get('student-passwords/reset', 'Student\Auth\ForgotPasswordController@showLinkRequestForm')->name('student-passwords.request');
Route::post('student-passwords/reset', 'Student\Auth\ResetPasswordController@reset');
Route::post('student-passwords/reset/{token}', 'Student\Auth\ResetPasswordController@showResetForm')->name('student-passwords.reset');
/////////////////////////////////////////////////

//parent routes
Route::post('parent-passwords/email', 'Parent\Auth\ForgotPasswordController@sendResetLinkEmail')->name('parent-passwords.email');
Route::get('parent-passwords/reset', 'Parent\Auth\ForgotPasswordController@showLinkRequestForm')->name('parent-passwords.request');
Route::post('parent-passwords/reset', 'Parent\Auth\ResetPasswordController@reset');
Route::post('parent-passwords/reset/{token}', 'Parent\Auth\ResetPasswordController@showResetForm')->name('parent-passwords.reset');
/////////////////////////////////////////////////

// staff routes
Route::post('staff-passwords/email', 'Staff\Auth\ForgotPasswordController@sendResetLinkEmail')->name('staff-passwords.email');
Route::get('staff-passwords/reset', 'Staff\Auth\ForgotPasswordController@showLinkRequestForm')->name('staff-passwords.request');
Route::post('staff-passwords/reset', 'Staff\Auth\ResetPasswordController@reset');
Route::post('staff-passwords/reset/{token}', 'Staff\Auth\ResetPasswordController@showResetForm')->name('staff-passwords.reset');
/////////////////////////////////////////////////


Route::get('register-admin', 'schoolAdmin\Auth\RegisterController@showRegistrationForm')->name('register-admin');
Route::post('register-admin', 'schoolAdmin\Auth\RegisterController@register');


// Route::get('/add_Admin', 'HomeController@index')->name('add_Admin');

Route::resource('add_admin', 'add_school_admin');

// Settings Routes
Route::get('/settings','Settings@index')->name('settings');
Route::get('/student-settings','StudentSettings@index');
Route::post('/student-settings','StudentSettings@update');
Route::get('/staff-settings','StaffSettings@index');
Route::post('/staff-settings','StaffSettings@update');//->name('settings');
Route::get('/parent-settings','ParentSettings@index');//->name('settings');
Route::post('/parent-settings','ParentSettings@update');
Route::get('/teacher-settings','TeacherSettings@index');//->name('settings');
Route::post('/teacher-settings','TeacherSettings@update');
Route::get('/admin-settings','SchoolAdminSettings@index');//->name('settings');
Route::post('/admin-settings','SchoolAdminSettings@update');
Route::get('/web-settings','WebAdminSettings@index');//->name('settings');
Route::post('/web-settings','WebAdminSettings@update');



//staff routes
Route::get('/staffEvents', 'StaffPagesController@staffEvents');
Route::post('/staffEvents','EventController@store');
Route::get('/staffMessages', 'StaffPagesController@staffMessages');
Route::get('/staffTeachers', 'StaffPagesController@staffTeachers');
Route::get('/staffCourses', 'StaffPagesController@staffCourses');
Route::post('/staffCourses','CourseController@store');
// Route::post('/staffStudents/{id}','studentController@index');
Route::post('/staffStudents/{id}', 'staffStudentController@edit');
Route::get('/staffStudentlist/{id}', 'staffStudentController@show');
Route::get('/staffStudentsprim', 'staffStudentController@index');
Route::get('/staffStudentsprep', 'staffStudentController@index');
Route::get('/staffStudentssec', 'staffStudentController@index');
Route::get('/staffClasses','ClassesController@index');
Route::post('/staffClasses','ClassesController@store');
Route::get('staffSchedules','ScheduleController@index');
Route::post('staffSchedules','ScheduleController@update');
Route::put('staffSchedules','ScheduleController@edit');
Route::get('staffTeachers','TeacherScheduleController@index');
//Route::post('staffTeachers','TeacherScheduleController@update');
Route::get('staffTeachers/{id}','TeacherScheduleController@indexSchedule');
Route::post('staffTeachers/{id}','TeacherScheduleController@store');
Route::get('DeleteClass/{id}','ClassesController@indexTeacher');
Route::delete('DeleteClass/{id}','ClassesController@destroy');


//parent routes
Route::get('/parent', 'PagesController@parent');
Route::get('/parent/parentTeacher', 'PagesController@parentTeacher');

// student routes
Route::get('student/student', 'Student\StudentController@index')->name('StudentHome');
Route::get('course/course/{indx}', 'Course\CourseController@index')->name('course');
Route::get('course/course', 'Course\CourseController@get_grade');

//school info routes
Route::resource('/Add_School_Info/add_School_info', 'schoolAdmin\addSchoolInfoController');
Route::resource('/Add_School_Info/add_staff_info', 'schoolAdmin\addStaffInfo');
Route::resource('/Add_School_Info/add_teacher_info','schoolAdmin\addTeacherInfoController');

//events route
Route::get('events','Eventcontroller@index')->name('event');

resources/views/Add_IT_Admin/add_IT_admin.blade.php
@extends('layouts.header')
{{-- @extends('layouts.footer') --}}

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 " style="padding-top: 115px">
            <div class="card">
                {{-- <div class="card-header">{{ __('Register') }}</div> --}}

                <div class="card-body" style="padding-top: 70px;">
                    <form method="POST" style="margin-bottom: 70px;" action="{{ route('add_admin.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required>

                                @if ($errors->has('email'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Phone Number') }}</label>

                            <div class="col-md-6">
                                <input id="phone" type="numeric" class="form-control {{ $errors->has('phone') ? ' is-invalid' : '' }}" name="phone" required>
                                @if ($errors->has('phone'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('phone') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="address" class="col-md-4 col-form-label text-md-right">{{ __('Address') }}</label>

                            <div class="col-md-6">
                                <input id="address" type="text" class="form-control {{ $errors->has('address') ? ' is-invalid' : '' }}" name="address" required>
                                @if ($errors->has('address'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('address') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Register') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection