routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|   
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//user's home routes 
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home_parent', 'ParentHomeController@index')->name('homeParent');
Route::get('/home_staff', 'StaffHomeController@index')->name('homeStaff');
Route::get('/home_student', 'StudentHomeController@index')->name('homeStudent');
Route::get('/home_teacher', 'TeacherHomeController@index')->name('homeTeacher');
Route::get('/home_web', 'WebController@index')->name('homeWeb');
//controlling user's home routes
Route::get('/Home', 'ControlHome@show')->name('Home');
//web admin login routes 
Route::get('webAdmin', 'webAdmin\Auth\LoginController@showLoginForm')->name('webAdmin');
Route::post('webAdmin', 'webAdmin\Auth\LoginController@login');
//controlling user's login routes
Route::get('login-admin', 'ControlLogin@showLoginForm')->name('login.admin');
Route::post('login-admin', 'ControlLogin@login');
//user's login routes 
Route::get('login-school', 'schoolAdmin\Auth\LoginController@showLoginForm')->name('school.login');
Route::post('login-school', 'schoolAdmin\Auth\LoginController@login');

Route::get('login-parent', 'Parent\Auth\LoginController@showLoginForm')->name('login.parent');
Route::post('login-parent', 'Parent\Auth\LoginController@login');

Route::get('login-student', 'Student\Auth\LoginController@showLoginForm')->name('login.student');
Route::post('login-student', 'Student\Auth\LoginController@login');

Route::get('login-staff', 'Staff\Auth\LoginController@showLoginForm')->name('login.staff');
Route::post('login-staff', 'Staff\Auth\LoginController@login');

Route::get('login-teacher', 'Teacher\Auth\LoginController@showLoginForm')->name('login.teacher');
Route::post('login-teacher', 'Teacher\Auth\LoginController@login');
//////////////////////////////////////////////

//forgot and reset pass
Route::get('forgotPass', 'ControlForgotPass@showEmail')->name('forgotPass');
Route::post('forgotPass', 'ControlForgotPass@reset');

//web admin routes
Route::post('web-passwords/email', 'webAdmin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('web-passwords.email');
Route::get('web-passwords/reset', 'webAdmin\Auth\ForgotPasswordController@showLinkRequestForm')->name('web-passwords.request');
Route::post('web-passwords/reset', 'webAdmin\Auth\ResetPasswordController@reset');
Route::post('web-passwords/reset/{token}', 'webAdmin\Auth\ResetPasswordController@showResetForm')->name('web-passwords.reset');
/////////////////////////////////////////////////

//school admin routes
Route::post('admin-passwords/email', 'schoolAdmin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin-passwords.email');
Route::get('admin-passwords/reset', 'schoolAdmin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin-passwords.request');
Route::post('admin-passwords/reset', 'schoolAdmin\Auth\ResetPasswordController@reset');
Route::post('admin-passwords/reset/{token}', 'schoolAdmin\Auth\ResetPasswordController@showResetForm')->name('admin-passwords.reset');
/////////////////////////////////////////////////

//teacher routes
Route::post('teacher-passwords/email', 'Teacher\Auth\ForgotPasswordController@sendResetLinkEmail')->name('teacher-passwords.email');
Route::get('teacher-passwords/reset', 'Teacher\Auth\ForgotPasswordController@showLinkRequestForm')->name('teacher-passwords.request');
Route::post('teacher-passwords/reset', 'Teacher\Auth\ResetPasswordController@reset');
Route::post('teacher-passwords/reset/{token}', 'Teacher\Auth\ResetPasswordController@showResetForm')->name('teacher-passwords.reset');
/////////////////////////////////////////////////

//student routes
Route::post('student-passwords/email', 'Student\Auth\ForgotPasswordController@sendResetLinkEmail')->name('student-passwords.email');
Route::get('student-passwords/reset', 'Student\Auth\ForgotPasswordController@showLinkRequestForm')->name('student-passwords.request');
Route::post('student-passwords/reset', 'Student\Auth\ResetPasswordController@reset');
Route::post('student-passwords/reset/{token}', 'Student\Auth\ResetPasswordController@showResetForm')->name('student-passwords.reset');
/////////////////////////////////////////////////

//parent routes
Route::post('parent-passwords/email', 'Parent\Auth\ForgotPasswordController@sendResetLinkEmail')->name('parent-passwords.email');
Route::get('parent-passwords/reset', 'Parent\Auth\ForgotPasswordController@showLinkRequestForm')->name('parent-passwords.request');
Route::post('parent-passwords/reset', 'Parent\Auth\ResetPasswordController@reset');
Route::post('parent-passwords/reset/{token}', 'Parent\Auth\ResetPasswordController@showResetForm')->name('parent-passwords.reset');
/////////////////////////////////////////////////

// staff routes
Route::post('staff-passwords/email', 'Staff\Auth\ForgotPasswordController@sendResetLinkEmail')->name('staff-passwords.email');
Route::get('staff-passwords/reset', 'Staff\Auth\ForgotPasswordController@showLinkRequestForm')->name('staff-passwords.request');
Route::post('staff-passwords/reset', 'Staff\Auth\ResetPasswordController@reset');
Route::post('staff-passwords/reset/{token}', 'Staff\Auth\ResetPasswordController@showResetForm')->name('staff-passwords.reset');
/////////////////////////////////////////////////


Route::get('register-admin', 'schoolAdmin\Auth\RegisterController@showRegistrationForm')->name('register-admin');
Route::post('register-admin', 'schoolAdmin\Auth\RegisterController@register');


// Route::get('/add_Admin', 'HomeController@index')->name('add_Admin');

Route::resource('add_admin', 'add_school_admin');

// Settings Routes
Route::get('/settings','Settings@index')->name('settings');
Route::get('/student-settings','StudentSettings@index');
Route::post('/student-settings','StudentSettings@update');
Route::get('/staff-settings','StaffSettings@index');
Route::post('/staff-settings','StaffSettings@update');//->name('settings');
Route::get('/parent-settings','ParentSettings@index');//->name('settings');
Route::post('/parent-settings','ParentSettings@update');
Route::get('/teacher-settings','TeacherSettings@index');//->name('settings');
Route::post('/teacher-settings','TeacherSettings@update');
Route::get('/admin-settings','SchoolAdminSettings@index');//->name('settings');
Route::post('/admin-settings','SchoolAdminSettings@update');
Route::get('/web-settings','WebAdminSettings@index');//->name('settings');
Route::post('/web-settings','WebAdminSettings@update');



//staff routes
Route::get('/staffEvents', 'StaffPagesController@staffEvents');
Route::post('/staffEvents','EventController@store');
Route::get('/staffMessages', 'StaffPagesController@staffMessages');
Route::get('/staffTeachers', 'StaffPagesController@staffTeachers');
Route::get('/staffCourses', 'StaffPagesController@staffCourses');
Route::post('/staffCourses','CourseController@store');
// Route::post('/staffStudents/{id}','studentController@index');
Route::post('/staffStudents/{id}', 'staffStudentController@edit');
Route::get('/staffStudentlist/{id}', 'staffStudentController@show');
Route::get('/staffStudentsprim', 'staffStudentController@index');
Route::get('/staffStudentsprep', 'staffStudentController@index');
Route::get('/staffStudentssec', 'staffStudentController@index');
Route::get('/staffClasses','ClassesController@index');
Route::post('/staffClasses','ClassesController@store');
Route::get('staffSchedules','ScheduleController@index');
Route::post('staffSchedules','ScheduleController@update');
Route::put('staffSchedules','ScheduleController@edit');
Route::get('staffTeachers','TeacherScheduleController@index');
//Route::post('staffTeachers','TeacherScheduleController@update');
Route::get('staffTeachers/{id}','TeacherScheduleController@indexSchedule');
Route::post('staffTeachers/{id}','TeacherScheduleController@store');
Route::get('DeleteClass/{id}','ClassesController@indexTeacher');
Route::delete('DeleteClass/{id}','ClassesController@destroy');


//parent routes
Route::get('/parent', 'PagesController@parent');
Route::get('/parent/parentTeacher', 'PagesController@parentTeacher');

// student routes
Route::get('student/student', 'Student\StudentController@index')->name('StudentHome');
Route::get('course/course/{indx}', 'Course\CourseController@index')->name('course');
Route::get('course/course', 'Course\CourseController@get_grade');

//school info routes
Route::resource('/Add_School_Info/add_School_info', 'schoolAdmin\addSchoolInfoController');
Route::resource('/Add_School_Info/add_staff_info', 'schoolAdmin\addStaffInfo');
Route::resource('/Add_School_Info/add_teacher_info','schoolAdmin\addTeacherInfoController');

//events route
Route::get('events','Eventcontroller@index')->name('event');

app/Http/Controllers/schoolAdmin/addSchoolInfoController.php
<?php

namespace App\Http\Controllers\schoolAdmin;
use Illuminate\Http\Request;
use  DB;
use App\Http\Controllers\Controller;
use App\school;
use Illuminate\Support\Facades\Auth;
use View;

class addSchoolInfoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
                return view('Add_School_info.add_School_info');
    }
    public function __construct()
    {
        $this->middleware('auth:admin');
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Add_School_Info.add_staff_info ');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    protected function guard()
    {
        return Auth::guard("admin");
    }
    public function store(Request $request)
    {

        $this->validate($request,[
            "name"=>'required|string|max:50',
            'inputPhone' => 'required|regex:/[0-9]/|max:11|min:8',
            'inputAddress' => 'required|string|min:3',
            'inputVision' => 'required|string|max:255',
            'inputMission' => 'required|string|max:255',
        ]);

    	$school=new school;
        $school->name=$request->name;
        $school->phone=$request->inputPhone;
        $school->address=$request->inputAddress ;
        $school->vision=$request->inputVision ;
        $school->mission=$request->inputMission;
        $school->admin_id=Auth::id();
        $school->save();
        session(['school_id' => $school->id]);
        return redirect('Add_School_Info/add_staff_info ')->with('school created successfully');

    	
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        return view('Add_School_info.add_School_info');
    
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

}

resources/views/Add_School_Info/add_School_info.blade.php
@extends('layouts.SAdminHeader')

@section('title')
Add school's info
@endsection
@section('css')
  <link rel="stylesheet" href="../css/add_school_info.css">

@endsection

@section('content')

<div class="container">


<form id="SchoolInfo" method= "post" action="{{ route('add_School_info.store') }}">
        @csrf
<div class="form-group col-md-6">
<label for="SInfo">{{ __('School Info') }}</label>
</div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <input type="text" id="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required autofocus  placeholder="Name">

       @if ($errors->has('name'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
    </div>

    <div class="form-group col-md-6">
      <input type="text" class="form-control{{ $errors->has('inputPhone') ? ' is-invalid' : '' }}" name="inputPhone" value="{{ old('inputPhone') }}" id="inputhone" placeholder="Phone" >

       @if ($errors->has('inputPhone'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('inputPhone') }}</strong>
                                    </span>
                                @endif
    </div>
  </div>


  <div class="form-group ">
    <input type="text" class="form-control{{ $errors->has('inputAddress') ? ' is-invalid' : '' }}" name="inputAddress" value="{{ old('inputAddress') }}"" id="inputAddress" placeholder="Address">

     @if ($errors->has('inputAddress'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('inputAddress') }}</strong>
                                    </span>
                                @endif
    </div>
  


  <div class="form-group ">
    <textarea class="form-control" id="inputVision" name="inputVision" placeholder="Vision" required></textarea> 
  </div>

  <div class="form-group ">
    <textarea class="form-control" id="inputMission" name="inputMission" placeholder="Mission" required></textarea> 
  </div>
    <button type="submit" class="btn btn-primary" >{{ __('Submit') }}</button>
</form>
</div>

@endsection



{{-- @extends('layout.header') --}}





   

resources/views/Add_School_Info/add_staff_info.blade.php
@extends('layouts.SAdminHeader')

@section('title')
Add staff's info
@endsection
@section('css')
  <link rel="stylesheet" href="../css/add_staff_info.css">

@endsection

@section('content')

<div class="container">
<div class="row">
<div class="col-sm-6 describe">
	<h2 style="font-weight: bold; font-style: italic; color: #ff99ff; font-size: 40px;">Here add information of staff </h2>
  <br>
  <p style="color: #cceeff; font-size: 25px;">  <span>Please fill all fields.
      To add more staff click (Save) button. If you finish hit (finish) button</span>  </p>
</div>
<div class="col-sm-6 ">
	

<form id="StaffInfo" method="post" action="add_staff_info">
        @csrf


  <div class="form-row">
    <div class="form-group col-md-6">
      <input type="text" id="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required autofocus  placeholder="Name">

       @if ($errors->has('name'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
    </div>

    <div class="form-group col-md-6">
      <input type="text" class="form-control{{ $errors->has('inputPhone') ? ' is-invalid' : '' }}" name="inputPhone" value="{{ old('inputPhone') }}" id="inputphone" placeholder="Phone" >

       @if ($errors->has('inputPhone'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('inputPhone') }}</strong>
                                    </span>
                                @endif
    </div>
  </div>
  <br>

<div class="form-row">
    <div class="form-group col-md-6">
      <input type="email" id="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required autofocus  placeholder="Email">

       @if ($errors->has('email'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
    </div>

    <div class="form-group col-md-6">
      <input type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" value="{{ old('password') }}" id="password" placeholder="Password" >

       @if ($errors->has('password'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
    </div>
  </div>
<br>
  <div class="form-group ">
    <input type="text" class="form-control{{ $errors->has('inputAddress') ? ' is-invalid' : '' }}" name="inputAddress" value="{{ old('inputAddress') }}"" id="inputAddress" placeholder="Address">

     @if ($errors->has('inputAddress'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('inputAddress') }}</strong>
                                    </span>
                                @endif
    </div>
  

<br>
  
    <button type="submit" class="btn btn-primary" >Save</button>
    <button type="button" class="btn btn-primary finish"><a href="{{ route('home') }}">Finish</a></button>
    <button type="button" class="btn btn-primary back" onclick="goBack()" >Back</button>
    {{-- <a  class="btn btn-primary finish" href="add_teacher_info">Finish</a> --}}
</form>
</div>
</div>
</div>

<script>
function goBack() {
    window.history.back();
}
</script>

@endsection








   